### ISSUE TITLE
你好，终于看到用Python写的了~感谢大佬，但是我在下载的时候报了如下错误

### ISSUE THREAD

**Issue by chaotianjiao** [lyp741/BaiduyunDownload#3]
Traceback (most recent call last):
  File "/Users/f/PycharmProjects/BaiduyunDownload/main.py", line 50, in run
    self.bdyd.bdy.Download_from_path(self.fname)
  File "/Users/f/PycharmProjects/BaiduyunDownload/DownloadBaiduYun.py", line 52, in Download_from_path
    self.Download_from_url(u,file_name)
  File "/Users/f/PycharmProjects/BaiduyunDownload/DownloadBaiduYun.py", line 69, in Download_from_url
    process.interact()
  File "/Users/f/PycharmProjects/only_for_study/tensorflow_venv/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 783, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (25, 'Inappropriate ioctl for device')

**Comment by chaotianjiao** [comment]
大佬可以帮我看看是什么问题吗~   感激不尽~

**Comment by chaotianjiao** [comment]
我解决了~    原来是在pycharm中运行的项目，后来改在zsh中执行python3 main.py就解决了，另外贴一张速度图：
![image](https://user-images.githubusercontent.com/42534375/68833590-d0020d80-06ee-11ea-8d26-53bed85136ae.png)
再一次感谢大佬!~

**Comment by lyp741** [comment]
试试直接在终端打开或者用可执行文件,应该是不能在pycharm打开。
